name: jupiter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  device_info: ^0.4.0+2
  firebase_messaging: ^5.1.6
  firebase_remote_config: ^0.2.0+7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  sqflite: "^1.1.5"
  path_provider: ^0.4.1
  http: ^0.12.0
  convert: 2.1.1
  dotp: ^1.0.2
  otp: 1.0.1


flutter_icons:
  image_path: "assets/icon/ItunesArtwork@2x.png"
  android: true
  ios: true
  #  adaptive_icon_background: "#ffffff"
  #  adaptive_icon_foreground: "#ffffff"


  dependency_overrides:
    image: 2.0.7
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
    - family: Lato-BlackItalic
      fonts:
        - asset: assets/fonts/Lato-BlackItalic.ttf
    - family: Lato-Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Lato-BoldItalic
      fonts:
        - asset: assets/fonts/Lato-BoldItalic.ttf
    - family: Lato-Hairline
      fonts:
        - asset: assets/fonts/Lato-Hairline.ttf
    - family: Lato-HairlineItalic
      fonts:
        - asset: assets/fonts/Lato-HairlineItalic.ttf
    - family: Lato-Italic
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf
    - family: Lato-LightItalic
      fonts:
        - asset: assets/fonts/Lato-LightItalic.ttf
    - family: Lato-Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Verlag-Black%20Italic
      fonts:
        - asset: assets/fonts/Verlag-Black%20Italic.otf
    - family: Verlag-Black
      fonts:
        - asset: assets/fonts/Verlag-Black.otf
    - family: Verlag-Black Italic
      fonts:
        - asset: assets/fonts/Verlag-Black Italic.otf
    - family: Verlag-Bold%20Italic
      fonts:
        - asset: assets/fonts/Verlag-Bold%20Italic.otf
    - family: Verlag-Bold
      fonts:
        - asset: assets/fonts/Verlag-Bold.otf
    - family: Verlag-Bold Italic
      fonts:
        - asset: assets/fonts/Verlag-Bold Italic.otf
    - family: Verlag-Book%20Italic
      fonts:
        - asset: assets/fonts/Verlag-Book%20Italic.otf
    - family: Verlag-Book
      fonts:
        - asset: assets/fonts/Verlag-Book.otf
    - family: Verlag-Book Italic
      fonts:
        - asset: assets/fonts/Verlag-Book Italic.otf
    - family: Verlag-Light%20Italic
      fonts:
        - asset: assets/fonts/Verlag-Light%20Italic.otf
    - family: Verlag-Light
      fonts:
        - asset: assets/fonts/Verlag-Light.otf
    - family: Verlag-Light Italic
      fonts:
        - asset: assets/fonts/Verlag-Light Italic.otf
    - family: Verlag-XLight%20Italic
      fonts:
        - asset: assets/fonts/Verlag-XLight%20Italic.otf
    - family: Verlag-XLight
      fonts:
        - asset: assets/fonts/Verlag-XLight.otf
    - family: Verlag-XLight Italic
      fonts:
        - asset: assets/fonts/Verlag-XLight Italic.otf

  assets:
    - assets/images/IOS Logo.png
    - assets/images/_640 x 960-7.png
    - assets/menu.json
  # - assets/database/local.db
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

